FROM base:1.0

RUN apt update && apt install -y --no-install-recommends sudo ssh build-essential gdb tar rsync ffmpeg libsm6 libxext6 && apt-get clean
RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_test_clion \
  && mkdir /run/sshd

RUN useradd -m user \
  && yes password | passwd user && adduser user sudo
RUN usermod -s /bin/bash user
ENV XDG_RUNTIME_DIR=/run/user/0
CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_test_clion"]

